apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  # deployment labels
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  replicas: 1
  # these are the labels replica set use to create  pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: database
  # this is pod definition
  template:
    metadata:
      labels:
        component: rabbitmq
        project: roboshop
        tier: database
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  selector:
    component: rabbitmq
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port