apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # deployment labels
  labels:
    purpose: mongodb
    project: roboshop
    tier: database
spec:
  replicas: 1
  # these are the labels replica set use to create  pod replicas, this should match pod labels
  selector:
    matchLabels:
      purpose: mongodb
      project: roboshop
      tier: database
  # this is pod definition
  template:
    metadata:
      labels:
        purpose: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mongodb
        image: joindevops/mongodb:v1

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    purpose: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    purpose: mongodb
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port